import { Alert, Share } from 'react-native';
import type { Instance, InstanceStep } from '../types';
import { formatDate } from './date';

async function getPrintModule() {
  try {
    return await import('expo-print');
  } catch {
    return null;
  }
}

async function getSharingModule() {
  try {
    return await import('expo-sharing');
  } catch {
    return null;
  }
}

export async function exportInstancePdf(
  instance: Instance,
  steps: InstanceStep[],
): Promise<void> {
  const doneSteps = steps.filter(s => s.status === 'done').length;

  const stepRows = steps.map((step, i) => `
    <tr>
      <td style="font-family: monospace; color: #8C6A4F; padding: 8px; border-bottom: 1px solid #D8D0C0; vertical-align: top; width: 40px;">
        ${(i + 1).toString().padStart(2, '0')}
      </td>
      <td style="padding: 8px; border-bottom: 1px solid #D8D0C0;">
        <strong style="color: #1F2A37;">${escapeHtml(step.title)}</strong>
        <span style="color: ${step.status === 'done' ? '#5B7A63' : '#8C6A4F'}; margin-left: 8px; font-size: 12px;">
          ${step.status.replace('_', ' ')}
        </span>
      </td>
    </tr>
    ${step.blocks.map(b => `
      <tr>
        <td></td>
        <td style="padding: 4px 8px 4px 16px; border-bottom: 1px solid #E8E2D6; font-size: 13px; color: #5A6570;">
          ${renderBlockForPdf(b)}
        </td>
      </tr>
    `).join('')}
  `).join('');

  const html = `
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body {
          font-family: -apple-system, Helvetica, Arial, sans-serif;
          color: #1F2A37;
          background: #FAF7F0;
          padding: 32px;
          max-width: 800px;
          margin: 0 auto;
        }
        h1 { font-size: 22px; font-weight: 600; color: #1F2A37; margin: 0; }
        .meta {
          color: #8B929A;
          font-size: 12px;
          font-family: Menlo, monospace;
          margin-top: 4px;
          margin-bottom: 24px;
        }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { margin-top: 32px; font-size: 11px; color: #8B929A; text-align: center; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(instance.name)}</h1>
      <div class="meta">
        ${escapeHtml(instance.template_title || '')} &middot;
        Started ${formatDate(instance.started_at)} &middot;
        ${doneSteps}/${steps.length} steps done
      </div>
      <table>${stepRows}</table>
      <div class="footer">Generated by ProcessTracker</div>
    </body>
    </html>
  `;

  const print = await getPrintModule();
  if (!print) {
    Alert.alert('Export not available', 'PDF export requires a development build with expo-print.');
    return;
  }

  try {
    const { uri } = await print.printToFileAsync({ html });
    const sharing = await getSharingModule();
    if (sharing && await sharing.isAvailableAsync()) {
      await sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Export Process Report',
      });
    } else {
      Alert.alert('PDF saved', `File at: ${uri}`);
    }
  } catch (e: any) {
    Alert.alert('Export failed', e.message);
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderBlockForPdf(block: any): string {
  switch (block.type) {
    case 'checklist_item':
      return `${block.completed ? '☑' : '☐'} ${escapeHtml(block.text_content || '')}`;
    case 'text':
      return escapeHtml(block.text_content || '');
    case 'link':
      return `🔗 ${escapeHtml(block.label || block.text_content || block.uri || '')}`;
    case 'photo':
      return `📷 ${block.text_content ? escapeHtml(block.text_content) : 'Photo attached'}`;
    case 'file':
      return `📎 ${escapeHtml(block.label || block.uri?.split('/').pop() || 'File attached')}`;
    default:
      return '';
  }
}
